### ISSUE TITLE
[BUG] 导入插件报错

### ISSUE THREAD

**Issue by secskb** [woodpecker-framework/woodpecker-framwork-release#12]
## 一、运行环境
* 操作系统： Windows11
* JDK版本：17.0.2
* woodpecker-framework版本： v1.3.3#20211124

## 二、问题描述
导入插件报错且使用插件报错
不加载插件
<img width="630" alt="afef419e52b66d0baf8ae57bb9df30d" src="https://user-images.githubusercontent.com/34313868/156515253-95fe44d9-0a17-4bad-9064-cdf484a64613.png">
加载插件
<img width="680" alt="60c75ea45be0882e8f7b10ebbc283a9" src="https://user-images.githubusercontent.com/34313868/156515599-022315fe-49cc-42aa-9073-4621d74528a4.png">
插件无法使用且报错

加载插件时报如下错误
className: me.gv7.woodpecker.plugin.WoodpeckerPluginManager
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:340)
        at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:282)
        at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:321)
        at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:234)
        at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:762)
        at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1033)
        at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:72)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:883)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:491)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at me.gv7.woodpecker.b.v.iIIiiiIIIii.loadClass(jc:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at me.gv7.woodpecker.b.c.iiIiIiIiiII.ALLATORIxDEMO(sc:222)
        at me.gv7.woodpecker.b.c.iiIiIiIiiII.ALLATORIxDEMO(sc:120)
        at me.gv7.woodpecker.gui.WoodpeckerGUI.d(ub:235)
        at me.gv7.woodpecker.gui.WoodpeckerGUI.ALLATORIxDEMO(ub:113)
        at me.gv7.woodpecker.gui.WoodpeckerGUI.main(ub:61)
java.lang.NoClassDefFoundError: javassist/NotFoundException
        at me.gv7.woodpecker.vuldb.XStreamVulPlugin.VulPluginMain(XStreamVulPlugin.java:33)
        at me.gv7.woodpecker.b.c.iiIiIiIiiII.ALLATORIxDEMO(sc:235)
        at me.gv7.woodpecker.b.c.iiIiIiIiiII.ALLATORIxDEMO(sc:63)
        at me.gv7.woodpecker.gui.WoodpeckerGUI.d(ub:235)
        at me.gv7.woodpecker.gui.WoodpeckerGUI.ALLATORIxDEMO(ub:113)
        at me.gv7.woodpecker.gui.WoodpeckerGUI.main(ub:61)
Caused by: java.lang.ClassNotFoundException: javassist.NotFoundException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at me.gv7.woodpecker.b.v.iIIiiiIIIii.loadClass(jc:44)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 6 more
## 三、bug产生的原因和建议
可能是JAVA版本不对，没去做测试

**Comment by Ppsoft1991** [comment]
这个可以手工删除signature file来解决，以后打包版本文我们会注意
